class Airplane:
    def __init__(self):
        self.speed = ...
        self .color = ...
        self.model = ...
        self.capacity = ...
        self.country = ...

    def turn_on(self):
        ...

    def turn_off(self):
        ...

    def fly(self):
        ...

class Car:
    def __init__(self):
        self.speed = ...
        self .color = ...
        self.model = ...
        self.capacity = ...
        self.country = ...
        self .number_wheels = ...
        self.licence_plat = ...

